# Generated by Django 3.2.12 on 2022-12-08 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('major', models.CharField(max_length=100)),
                ('grad_year', models.IntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('linkedin', models.URLField(blank=True, unique=True)),
                ('intro', models.TextField(null=True)),
                ('preferred_mentee_grade', models.CharField(blank=True, choices=[('FR', '高一'), ('S0', '高二'), ('SR', '高三')], max_length=100, null=True)),
                ('other_preferences', models.TextField(blank=True, null=True)),
                ('essay_editing', models.BooleanField(default=True)),
                ('uni', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school.uni')),
            ],
        ),
    ]
